#!/usr/bin/env perl
use strict;
use warnings;

##================================================================
use Cwd 'abs_path';
use File::Spec::Functions ('catpath', 'splitpath');
use lib catpath((splitpath(abs_path $0))[0, 1], 'blib/lib/perl5');
my $PATH = (splitpath(abs_path $0))[0, 1];
##================================================================

my @modules = (
   'CPAN::Meta',
   'IO::Compress::Gzip',
   'Term::ANSIColor',
   'Cpanel::JSON::XS',
   'File::PAth',
   'YAML::XS',
   'IO::All',
   'Try::Tiny',
);

# Core modules
#  'File::Find',
#  'Config'
#  'Module::CoreList'
#  'Term::ANSIColor' ??

unless ( eval { require Extlib } ) {

    my @commands = (
        './extlib/cpanm',
        '--mirror', "$PATH/src",
        '--mirror-only',
        '--notest',
        '--quiet',
        '-L', "./extlib/blib",
        @modules,
    );

    print "installing packages required by extlib\n";
    system @commands;
    print "installed\n";
}

