#!/usr/bin/env perl

use strict;
use warnings;

=head1 update-src

This script executes a carton update method in CE::Carton.

The module.yaml is used for specifying the required modules.

In order to gather the metadata and create the carton.lock file,
an actual install is run into extlib/lib. Then carton gathers
the metadata from the installed packages, from the architecture .meta
directory, such as: extlib/lib/perl5/x86_64-linux-gnu-thread-multi/.meta

After creating the carton.lock file, an 02packages.details.txt file is
created in extlib/etc.

=cut

##================================================================
use Cwd 'abs_path';
use File::Spec::Functions ('catpath', 'splitpath');
use lib catpath((splitpath(abs_path $0))[0, 1], 'blib/lib/perl5');
my $PATH = (splitpath(abs_path $0))[0, 1];
require "${PATH}extlib_config.pm";
my $Config = extlib_config->Config;
##================================================================

use Extlib;

use constant { SUCCESS => 0, INFO => 1, WARN => 2, ERROR => 3 };
my $extlib = Extlib->new( %Config );

$extlib->print("Checking update\n", INFO);

$extlib->check_meta_for_update( 'verbose' );

$extlib->print("Check above information for validity. If good, execute extlib/build-metadata\n", INFO);
$extlib->print("If not good, modify modules.yaml and run extlib/update-package and extlib/check-update until it's correct\n", INFO);

