#!/usr/bin/env perl

use strict;
use warnings;

=head1 install-not-installed

This script installs modules passed in on the command line.

The equivalent can be done by:

   cpanm -L extlib --mirror-only --mirror ~/<repo_path>/extlib/src Crypt::SaltedHash

=cut

##================================================================
use Cwd 'abs_path';
use File::Spec::Functions ('catpath', 'splitpath');
use lib catpath((splitpath(abs_path $0))[0, 1], 'eblib/lib/perl5');
my $PATH = (splitpath(abs_path $0))[0, 1];
require "${PATH}extlib_config.pm";
my $Config = extlib_config->Config;
##================================================================

use Extlib;;
my $extlib = Extlib->new( %$Config );

my $modules = $extlib->meta_needs_install;
$extlib->install( modules => $modules );

