#!/usr/bin/env perl

=head1 verify-update

After building new source, run this to make sure everything installs ok.

=cut

# use extlib/eblib as a build library
use Cwd 'abs_path';
use File::Spec::Functions qw(catpath splitpath);
use lib catpath((splitpath(abs_path $0))[0, 1], 'eblib/lib/perl5');

use Extlib;;

my $extlib = Extlib->new(
    path => 'extlib',
    modspec_file => 'extlib/etc/modules.yaml',
    mirror_meta_file => 'extlib/etc/extlib.json',
    cpanm_executable => 'extlib/cpanm',
);

$extlib->install_full;
$extlib->check_installed_against_mirror_meta;
