#!/usr/bin/env perl

=head1 verify-update

After building new source, run this to make sure everything installs ok.

=cut

##================================================================
use Cwd 'abs_path';
use File::Spec::Functions ('catpath', 'splitpath');
use lib catpath((splitpath(abs_path $0))[0, 1], 'eblib/lib/perl5');
my $PATH = (splitpath(abs_path $0))[0, 1];
require "${PATH}extlib_config.pm";
my $Config = extlib_config->Config;
##================================================================

use Extlib;;

my $extlib = Extlib->new( %$Config );

$extlib->install_full;
$extlib->check_installed_against_mirror_meta;
